# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002d89b0b0647424e8a79f82c46bc12c6e7f37648c976b941b7fa072c3cba3448923020a5de8df3fd750f00c4326a56f86579b6166238a029c7a2dadac867975

test:
  secret_key_base: ebcf2b8c202bfbd0af111c294bb27ae6e517f424b8be429fa9d6909cddaa84d141848691114b13aaf8866adff89fd7fdd7efb2acbcfcd6cc6865bc87ccb9bf04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
